#*
#  Copyright (C) 2001 Jimchyun Huang
#
# This file is subject to the terms and conditions of the GNU General
# Public License.  See the file "COPYING" in the main directory of
# this archive for more details.
	 
SUBDIRS = src/stdio src/stdlib src/string src/dev
include ../recurse.rules

