TOPDIR = ..

BIN_NAME = boot.bin

all:
	$(ASM) boot.asm -o $(BIN_NAME)

clean:
	rm -f $(BIN_NAME)

include $(TOPDIR)/assembler.inc                                                                     
